### PR TITLE
Remove comment from tee.c

### PR DESCRIPTION
**Pull request by kiyotakamori**
I read src/tee.c source code. 
I found some comments which no longer use so I deleted some comments to improve readability.
If it's useful comments, I have to say sorry. Could you merge this commit if my change is useful?

### CODE REVIEW

**Comment by cheat-sc** [comment]
Thank you for your contribution! It looks like good.

I would like you to change the commit message as the following:

_Delete some comments to improve readability._

Why?

- Use imperative form

from https://github.com/RomuloOliveira/commit-messages-guide/blob/master/README.md

The article has many good practices, so I recommend to read it.

**Comment by kiyotakamori** [comment]
I appriciate your advice and recommendation. 
It's much useful info for me. I'd like to change my commit message by following your advice.

**Comment by cheat-sc** [comment]
Do you have any updates? If "No", I will merge this PR!

**Comment by kiyotakamori** [comment]
No, I don't.
Thank you for telling me that.

**Pull request merged**
